from typing import Protocol, Any

from src.domain.models.posts import PostRead, PostCreate, PostUpdate


class PostsRepository(Protocol):
    async def get(self, id: Any) -> PostRead: ...
    async def get_all_by_author(self, author_id: Any) -> list[PostRead]: ...
    async def create(self, obj: PostCreate, id: Any, author_id: Any) -> PostRead: ...
    async def update(self, obj: PostUpdate, id: Any) -> PostRead: ...
    async def delete(self, id: Any) -> bool: ...
    async def get_all(self) -> list[PostRead]: ...
