from typing import Any, Protocol

from src.domain.models.users import UserCreate, UserRead, UserUpdate


class UserRepository(Protocol):
    async def get(self, id: Any) -> UserRead: ...
    async def get_all(self) -> list[UserRead]: ...
    async def create(self, obj: UserCreate, id: Any) -> UserRead: ...
    async def update(self, obj: UserUpdate, id: Any) -> UserRead: ...
    async def delete(self, id: Any) -> bool: ...
